import DashboardLayout from "@/components/DashboardLayout";
import { adminMenu } from "@/lib/adminNavigation";
import { trpc } from "@/lib/trpc";
import { KeyRound, Save } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function AdminSpecialAccess() {
  const utils = trpc.useUtils();
  const pages = trpc.admin.specialAccess.useQuery();
  const [notes, setNotes] = useState<Record<number, string>>({});
  const update = trpc.admin.updateSpecialAccess.useMutation({ onSuccess: async () => { await utils.admin.specialAccess.invalidate(); toast.success("Estado atualizado."); }, onError: error => toast.error(error.message) });
  return <DashboardLayout menuItems={adminMenu} title="Administração"><main className="mx-auto w-full max-w-6xl space-y-6 p-5 sm:p-8"><header className="space-y-2"><span className="text-xs uppercase tracking-[.16em] text-amber-300">Gestão de acesso</span><h1 className="text-3xl font-semibold text-white">Mensagens senha especial</h1><p className="max-w-3xl text-sm leading-6 text-zinc-300">Acompanhe as páginas privadas criadas pelos membros, pause publicações e registre orientações operacionais. Senhas nunca são exibidas nesta área.</p></header><section className="overflow-hidden rounded-2xl border border-white/10 bg-zinc-950/60"><div className="border-b border-white/10 p-5"><div className="flex items-center gap-2 text-white"><KeyRound className="size-5 text-amber-300" /><h2 className="font-medium">Páginas configuradas</h2></div></div>{pages.isLoading ? <p className="p-5 text-sm text-zinc-400">Carregando páginas...</p> : !pages.data?.length ? <p className="p-5 text-sm text-zinc-400">Nenhum membro configurou uma página especial ainda.</p> : <div className="divide-y divide-white/10">{pages.data.map(page => <article key={page.id} className="space-y-4 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-medium text-white">{page.title}</h3><p className="mt-1 text-sm text-zinc-400">{page.memberName ?? "Membro"} · {page.memberEmail ?? "E-mail indisponível"}</p><p className="mt-2 text-xs text-zinc-500">Código: {page.publicCode} · {page.accessCount} acessos</p></div><span className="rounded-full border border-white/15 px-2.5 py-1 text-xs uppercase tracking-wider text-amber-200">{page.status}</span></div><div className="grid gap-3 md:grid-cols-[180px_minmax(0,1fr)_auto]"><select aria-label={`Status de ${page.title}`} defaultValue={page.status} onChange={event => update.mutate({ id: page.id, status: event.target.value as "draft" | "published" | "paused", adminNote: notes[page.id] || null })} className="rounded-lg border border-white/15 bg-black px-3 py-2 text-sm text-white"><option value="draft">Rascunho</option><option value="published">Publicado</option><option value="paused">Pausado</option></select><input value={notes[page.id] ?? page.adminNote ?? ""} onChange={event => setNotes({ ...notes, [page.id]: event.target.value })} maxLength={2000} placeholder="Orientação administrativa opcional" className="rounded-lg border border-white/15 bg-black px-3 py-2 text-sm text-white" /><button type="button" onClick={() => update.mutate({ id: page.id, status: page.status, adminNote: notes[page.id] ?? page.adminNote ?? null })} className="inline-flex items-center justify-center gap-2 rounded-lg border border-white/15 px-3 py-2 text-sm text-white"><Save className="size-4" />Salvar nota</button></div></article>)}</div>}</section></main></DashboardLayout>;
}
