import DashboardLayout, { type DashboardMenuItem } from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, BookOpenCheck, CheckCircle2, GraduationCap, LayoutDashboard, LoaderCircle, PlayCircle } from "lucide-react";
import { toast } from "sonner";
import { useLocation } from "wouter";

const menu: DashboardMenuItem[] = [
  { icon: LayoutDashboard, label: "Escritório", path: "/membros", group: "Navegação" },
  { icon: GraduationCap, label: "Academia", path: "/membros/academia", group: "Crescimento" },
  { icon: BookOpenCheck, label: "Biblioteca de e-books", path: "/membros/ebooks", group: "Crescimento" },
];

const levelLabel = { fundamentos: "Fundamentos", pratica: "Prática", avancado: "Avançado" } as const;

export default function MemberCourses() {
  const [location, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const courses = trpc.member.courses.useQuery();
  const routeKey = location === "/membros/academia" ? null : location.replace(/^\/membros\/curso\//, "").replace(/^\/membros\//, "");
  const currentCourse = trpc.member.course.useQuery({ routeKey: routeKey || "curso" }, { enabled: Boolean(routeKey) });
  const updateProgress = trpc.member.updateCourseProgress.useMutation({
    onSuccess: () => { void utils.member.courses.invalidate(); void utils.member.academy.invalidate(); void utils.member.course.invalidate(); toast.success("Progresso atualizado."); },
    onError: error => toast.error(error.message),
  });
  if (routeKey) {
    const course = currentCourse.data;
    return <DashboardLayout menuItems={menu} title="Escritório Virtual"><main className="mx-auto w-full max-w-7xl space-y-5 p-4 sm:p-8"><button type="button" onClick={() => setLocation("/membros/academia")} className="inline-flex items-center gap-2 text-sm font-medium text-amber-200 transition hover:text-amber-100"><ArrowLeft className="size-4" />Voltar para a Academia</button>{currentCourse.isLoading ? <section className="flex min-h-96 items-center justify-center gap-2 rounded-2xl border border-white/10 bg-zinc-950/60 text-sm text-zinc-400"><LoaderCircle className="size-4 animate-spin text-amber-300" />Abrindo material de estudo...</section> : course ? <section className="overflow-hidden rounded-2xl border border-white/10 bg-zinc-950/60"><header className="border-b border-white/10 p-4 sm:p-6"><span className="text-xs uppercase tracking-[0.16em] text-amber-300">{course.category || "Área de estudo"} · {levelLabel[course.level]}</span><h1 className="mt-2 text-2xl font-semibold text-white sm:text-3xl">{course.title}</h1>{course.summary && <p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-300">{course.summary}</p>}<div className="mt-4 flex flex-wrap items-center gap-3"><span className="text-sm text-zinc-400">Progresso: <strong className="text-amber-200">{course.progressPercent}%</strong></span><button type="button" disabled={updateProgress.isPending || course.progressPercent >= 100} onClick={() => updateProgress.mutate({ courseId: course.id, progressPercent: Math.min(100, course.progressPercent + 20) })} className="rounded-lg bg-amber-300 px-3 py-2 text-sm font-semibold text-black disabled:opacity-50">{course.progressPercent >= 100 ? "Concluído" : "Registrar avanço"}</button><button type="button" disabled={updateProgress.isPending || course.progressPercent === 100} onClick={() => updateProgress.mutate({ courseId: course.id, progressPercent: 100 })} className="inline-flex items-center gap-1 rounded-lg border border-white/15 px-3 py-2 text-sm text-zinc-100 disabled:opacity-50"><CheckCircle2 className="size-4" />Concluir leitura</button></div></header><div className="bg-black/20 p-2 sm:p-4"><iframe title={`Leitor de ${course.ebook.title}`} sandbox="" srcDoc={course.ebook.htmlContent} className="h-[72vh] min-h-[560px] w-full rounded-xl border border-white/10 bg-white" /></div></section> : <section className="rounded-2xl border border-amber-300/30 bg-amber-300/5 p-6"><h1 className="text-xl font-semibold text-white">Material indisponível</h1><p className="mt-2 text-sm leading-6 text-zinc-300">Este curso não está publicado ou não possui um e-book disponível no momento. Volte à Academia para escolher outro material.</p></section>}</main></DashboardLayout>;
  }
  return <DashboardLayout menuItems={menu} title="Escritório Virtual"><main className="mx-auto w-full max-w-7xl space-y-7 p-5 sm:p-8"><header className="space-y-2"><span className="text-xs uppercase tracking-[0.16em] text-amber-300">Área de estudo</span><h1 className="text-3xl font-semibold text-white">Academia Página Lucrativa</h1><p className="max-w-3xl text-sm leading-6 text-zinc-300">Selecione uma formação para abrir o e-book no leitor integrado. O progresso é individual e fica salvo no seu Escritório Virtual.</p></header>{courses.isLoading ? <p className="text-sm text-zinc-400">Carregando cursos...</p> : courses.data?.length ? <section className="grid gap-4 lg:grid-cols-2">{courses.data.map(course => <article key={course.id} className="rounded-2xl border border-white/10 bg-zinc-950/60 p-5"><div className="flex items-start justify-between gap-3"><div><span className="text-xs uppercase tracking-wider text-amber-200">{course.category || "Formação"} · {levelLabel[course.level]}</span><h2 className="mt-2 text-xl font-semibold text-white">{course.title}</h2><p className="mt-2 text-sm leading-6 text-zinc-300">{course.summary || "Material de estudo disponível na Academia."}</p></div><GraduationCap className="size-6 shrink-0 text-amber-300" /></div><div className="mt-5 border-t border-white/10 pt-4"><div className="flex items-center justify-between text-sm"><span className="text-zinc-400">Progresso individual</span><strong className="text-amber-200">{course.progressPercent}%</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-amber-300 transition-all" style={{ width: `${course.progressPercent}%` }} /></div><div className="mt-4 flex flex-wrap items-center gap-2"><button type="button" onClick={() => setLocation(`/membros/curso/${course.routeKey}`)} className="inline-flex items-center gap-1 rounded-lg bg-amber-300 px-3 py-2 text-sm font-semibold text-black"><PlayCircle className="size-4" />Abrir material</button><button type="button" disabled={updateProgress.isPending || course.progressPercent >= 100} onClick={() => updateProgress.mutate({ courseId: course.id, progressPercent: Math.min(100, course.progressPercent + 20) })} className="rounded-lg border border-white/15 px-3 py-2 text-sm text-zinc-100 disabled:opacity-50">{course.progressPercent >= 100 ? "Concluído" : "Avançar 20%"}</button><span className="ml-auto text-xs text-zinc-500">{course.durationMinutes ? `${course.durationMinutes} min` : "Duração a definir"}</span></div></div></article>)}</section> : <section className="rounded-2xl border border-dashed border-white/15 bg-zinc-950/40 p-7 text-sm leading-6 text-zinc-300">Nenhum curso com material publicado está disponível no momento. A administração pode vincular e publicar novos conteúdos pela Academia.</section>}</main></DashboardLayout>;
}
