import DashboardLayout from "@/components/DashboardLayout";
import { withAppBase } from "@/lib/devPath";
import { memberDashboardMenuItems } from "@/lib/memberDashboardNavigation";
import { applicationStatusLabel } from "@shared/applications";
import { trpc } from "@/lib/trpc";
import { ClipboardList, Link2 } from "lucide-react";

export default function MemberAffiliateOrders() {
  const profile = trpc.member.profile.useQuery();
  const orders = trpc.member.affiliateApplications.useQuery();
  const personalLink = profile.data?.slug ? `${window.location.origin}/?afiliado=${encodeURIComponent(profile.data.slug)}` : null;
  return <DashboardLayout menuItems={memberDashboardMenuItems} title="Escritório Virtual"><main className="mx-auto w-full max-w-5xl space-y-7 p-5 sm:p-8"><header className="space-y-2"><span className="text-xs uppercase tracking-[.16em] text-emerald-300">Pedidos da operação</span><h1 className="text-3xl font-semibold text-white">Solicitações atribuídas</h1><p className="max-w-3xl text-sm leading-6 text-zinc-300">Acompanhe apenas as solicitações originadas pelo seu link pessoal. A atribuição identifica a origem do pedido, mas não transforma automaticamente a solicitação em venda, pagamento ou ganho.</p></header><section className="rounded-2xl border border-emerald-300/20 bg-emerald-300/5 p-5"><div className="flex items-start gap-3"><Link2 className="mt-0.5 size-5 shrink-0 text-emerald-300" /><div><h2 className="font-medium text-white">Seu link pessoal</h2>{personalLink ? <><code className="mt-2 block break-all rounded-lg bg-black/40 p-3 text-sm text-emerald-100">{personalLink}</code><p className="mt-2 text-sm text-zinc-300">Solicitações enviadas por esse endereço podem ser atribuídas ao seu Escritório Virtual para acompanhamento.</p></> : <p className="mt-2 text-sm text-zinc-300">Defina seu identificador em <a href={withAppBase("/membros/configuracoes")} className="text-emerald-200 underline">Editar perfil</a> para ativar o link pessoal.</p>}</div></div></section><section className="overflow-hidden rounded-2xl border border-white/10 bg-zinc-950/60"><div className="flex items-center justify-between gap-3 border-b border-white/10 p-5"><div className="flex items-center gap-2 text-white"><ClipboardList className="size-5 text-emerald-300" /><h2 className="font-medium">Solicitações atribuídas</h2></div><span className="text-xs uppercase tracking-wider text-zinc-500">{orders.data?.length ?? 0} pedidos</span></div>{orders.isLoading ? <p className="p-5 text-sm text-zinc-400">Carregando pedidos...</p> : orders.data?.length ? <div className="divide-y divide-white/10">{orders.data.map(order => <article key={order.id} className="grid gap-2 p-5 sm:grid-cols-[1fr_auto]"><div><p className="font-medium text-white">{order.trackingCode}</p><p className="mt-1 text-sm text-zinc-400">Solicitação registrada em {new Date(order.createdAt).toLocaleString("pt-BR")}</p></div><span className="text-sm text-emerald-200">{applicationStatusLabel[order.status]}</span></article>)}</div> : <div className="p-7 text-sm leading-6 text-zinc-300"><p className="font-medium text-white">Ainda não há solicitações atribuídas ao seu link.</p><p className="mt-1 text-zinc-400">Quando uma pessoa enviar um pedido pelo endereço acima, a solicitação poderá aparecer nesta carteira com seu código e status.</p></div>}</section></main></DashboardLayout>;
}
