import DashboardLayout from "@/components/DashboardLayout";
import { memberDashboardMenuItems } from "@/lib/memberDashboardNavigation";
import { applicationStatusLabel } from "@shared/applications";
import { trpc } from "@/lib/trpc";
import { ClipboardList, Link2 } from "lucide-react";

export default function MemberAffiliateOrders() {
  const profile = trpc.member.profile.useQuery();
  const orders = trpc.member.affiliateApplications.useQuery();
  const personalLink = profile.data?.slug ? `${window.location.origin}/?afiliado=${encodeURIComponent(profile.data.slug)}` : null;
  return <DashboardLayout menuItems={memberDashboardMenuItems} title="Escritório Virtual"><main className="mx-auto w-full max-w-5xl space-y-7 p-5 sm:p-8"><header className="space-y-2"><span className="text-xs uppercase tracking-[.16em] text-amber-300">Atuação como afiliado</span><h1 className="text-3xl font-semibold text-white">Meus pedidos</h1><p className="max-w-3xl text-sm leading-6 text-zinc-300">Acompanhe apenas as solicitações originadas pelo seu link pessoal. O administrador também utiliza esta carteira quando atua como afiliado, mantendo a gestão global em área separada.</p></header><section className="rounded-2xl border border-amber-300/20 bg-amber-300/5 p-5"><div className="flex items-start gap-3"><Link2 className="mt-0.5 size-5 shrink-0 text-amber-300" /><div><h2 className="font-medium text-white">Seu link de indicação</h2>{personalLink ? <><code className="mt-2 block break-all rounded-lg bg-black/40 p-3 text-sm text-amber-100">{personalLink}</code><p className="mt-2 text-sm text-zinc-300">Pedidos enviados por esse endereço ficam vinculados ao seu Escritório Virtual.</p></> : <p className="mt-2 text-sm text-zinc-300">Defina seu identificador em <a href="/membros/configuracoes" className="text-amber-200 underline">Editar perfil</a> para ativar o link pessoal.</p>}</div></div></section><section className="overflow-hidden rounded-2xl border border-white/10 bg-zinc-950/60"><div className="flex items-center justify-between gap-3 border-b border-white/10 p-5"><div className="flex items-center gap-2 text-white"><ClipboardList className="size-5 text-amber-300" /><h2 className="font-medium">Carteira atribuída</h2></div><span className="text-xs uppercase tracking-wider text-zinc-500">{orders.data?.length ?? 0} pedidos</span></div>{orders.isLoading ? <p className="p-5 text-sm text-zinc-400">Carregando pedidos...</p> : orders.data?.length ? <div className="divide-y divide-white/10">{orders.data.map(order => <article key={order.id} className="grid gap-2 p-5 sm:grid-cols-[1fr_auto]"><div><p className="font-medium text-white">{order.trackingCode}</p><p className="mt-1 text-sm text-zinc-400">Solicitação registrada em {new Date(order.createdAt).toLocaleString("pt-BR")}</p></div><span className="text-sm text-amber-200">{applicationStatusLabel[order.status]}</span></article>)}</div> : <div className="p-7 text-sm leading-6 text-zinc-300"><p className="font-medium text-white">Ainda não há pedidos atribuídos ao seu link.</p><p className="mt-1 text-zinc-400">Divulgue o endereço acima. O próximo pedido enviado por ele aparecerá nesta carteira.</p></div>}</section></main></DashboardLayout>;
}
