ALTER TABLE memberProfiles
  ADD COLUMN IF NOT EXISTS facebookUrl VARCHAR(512) NULL AFTER photoUrl,
  ADD COLUMN IF NOT EXISTS twitterUrl VARCHAR(512) NULL AFTER facebookUrl,
  ADD COLUMN IF NOT EXISTS linkedinUrl VARCHAR(512) NULL AFTER twitterUrl,
  ADD COLUMN IF NOT EXISTS youtubeUrl VARCHAR(512) NULL AFTER linkedinUrl,
  ADD COLUMN IF NOT EXISTS skype VARCHAR(255) NULL AFTER youtubeUrl,
  ADD COLUMN IF NOT EXISTS address VARCHAR(255) NULL AFTER skype,
  ADD COLUMN IF NOT EXISTS addressNumber VARCHAR(32) NULL AFTER address,
  ADD COLUMN IF NOT EXISTS addressComplement VARCHAR(160) NULL AFTER addressNumber,
  ADD COLUMN IF NOT EXISTS postalCode VARCHAR(20) NULL AFTER addressComplement,
  ADD COLUMN IF NOT EXISTS district VARCHAR(120) NULL AFTER postalCode,
  ADD COLUMN IF NOT EXISTS city VARCHAR(120) NULL AFTER district,
  ADD COLUMN IF NOT EXISTS state VARCHAR(80) NULL AFTER city;
