import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const root = process.cwd();
describe("fluxo de indicações", () => {
  it("mantém a entidade, leitura administrativa e vínculo automático sem criação manual", () => {
    const schema = readFileSync(resolve(root, "drizzle/schema.ts"), "utf8");
    const router = readFileSync(resolve(root, "server/routers.ts"), "utf8");
    const app = readFileSync(resolve(root, "client/src/App.tsx"), "utf8");
    const db = readFileSync(resolve(root, "server/db.ts"), "utf8");
    const adminReferrals = readFileSync(resolve(root, "client/src/pages/AdminReferrals.tsx"), "utf8");
    const adminOffice = readFileSync(resolve(root, "client/src/pages/AdminOffice.tsx"), "utf8");
    const memberReferrals = readFileSync(resolve(root, "client/src/pages/MemberReferrals.tsx"), "utf8");
    const guards = readFileSync(resolve(root, "server/integrityGuards.ts"), "utf8");
    expect(schema).toContain('mysqlTable("referralLinks"');
    expect(schema).toContain("referredUserId");
    expect(router).toContain("referrals: protectedProcedure");
    expect(router).toContain("referralLinks: adminProcedure.query");
    expect(router).not.toContain("setReferralLink: adminProcedure");
    expect(db).toContain("application.ownerUserId, referredUserId: userId");
    expect(db).toContain("activeCount");
    expect(db).toContain("sponsorCount");
    expect(db).toContain("referredCount");
    expect(db).toContain("assertSponsorImmutable");
    expect(db).toContain("db.transaction(async tx =>");
    expect(db).not.toContain("set: { sponsorId: application.ownerUserId, status: \"active\" }");
    expect(adminReferrals).toContain("Gerencie contas, bloqueios e exclusões com retenção de 7 dias");
    expect(adminReferrals).toContain("Os vínculos continuam sendo criados pelo fluxo real de adesão.");
    expect(adminReferrals).toContain("data?.activeCount");
    expect(adminReferrals).not.toContain("createReferral");
    expect(adminReferrals).not.toContain("Vincular indicação");
    expect(adminOffice).toContain("Consulte vínculos de indicação criados pelo fluxo de adesão.");
    expect(memberReferrals).toContain("network.error");
    expect(memberReferrals).toContain("Tentar novamente");
    expect(guards).toContain("assertReceiptUploadAllowed");
    expect(guards).toContain("assertReceiptReviewAllowed");
    expect(app).toContain('path="/membros/rede"');
    expect(app).toContain('path="/admin/membros"');
  });
});
