import { trpc } from "@/lib/trpc";
import { History, ShieldCheck, UsersRound } from "lucide-react";
import { toast } from "sonner";

type ContactStatus = "new" | "contacted" | "qualified" | "archived";
export default function AdminCapturePanel() {
  const utils = trpc.useUtils();
  const contacts = trpc.admin.contacts.useQuery();
  const activities = trpc.admin.activities.useQuery();
  const updateContact = trpc.admin.updateContact.useMutation({ onSuccess: async () => { await Promise.all([utils.admin.contacts.invalidate(), utils.admin.activities.invalidate(), utils.member.contacts.invalidate(), utils.member.activities.invalidate()]); toast.success("Status do contato atualizado."); }, onError: error => toast.error(error.message) });
  return <section className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><div className="rounded-2xl border border-white/10 bg-zinc-950/60 p-5"><div className="flex items-center gap-2 text-white"><UsersRound size={18} className="text-amber-300" /><div><h2 className="font-medium">Captação consentida</h2><p className="mt-1 text-sm font-normal text-zinc-400">Supervisione os registros necessários à operação. Não há disparos automáticos nem importação de listas.</p></div></div>{contacts.isLoading ? <p className="mt-4 text-sm text-zinc-400">Carregando contatos...</p> : contacts.data?.length ? <div className="mt-4 space-y-3">{contacts.data.map(item => <article key={item.id} className="rounded-xl border border-white/10 bg-black/30 p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><h3 className="font-medium text-white">{item.name}</h3><p className="text-sm text-zinc-400">{item.email}{item.whatsapp ? ` · ${item.whatsapp}` : ""}</p><p className="mt-1 text-xs text-amber-200">Origem: {item.source} · consentimento registrado em {new Date(item.consentAt).toLocaleDateString("pt-BR")}</p>{item.consentNote && <p className="mt-2 text-sm text-zinc-300">{item.consentNote}</p>}</div><select value={item.status} onChange={e => updateContact.mutate({ id: item.id, status: e.target.value as ContactStatus })} disabled={updateContact.isPending} className="h-9 rounded-lg border border-white/15 bg-black px-2 text-sm text-white"><option value="new">Novo</option><option value="contacted">Contatado</option><option value="qualified">Qualificado</option><option value="archived">Arquivado</option></select></div></article>)}</div> : <p className="mt-4 text-sm text-zinc-400">Nenhum contato consentido foi registrado.</p>}</div><div className="rounded-2xl border border-white/10 bg-zinc-950/60 p-5"><div className="flex items-center gap-2 text-white"><History size={18} className="text-amber-300" /><h2 className="font-medium">Trilha operacional</h2></div>{activities.data?.length ? <div className="mt-4 space-y-3">{activities.data.map(item => <article key={item.id} className="border-l-2 border-amber-300/60 pl-3"><div className="flex items-center gap-2"><ShieldCheck size={14} className="text-amber-300" /><p className="text-sm text-zinc-200">{item.description}</p></div><p className="mt-1 text-xs text-zinc-500">{new Date(item.createdAt).toLocaleString("pt-BR")}</p></article>)}</div> : <p className="mt-4 text-sm text-zinc-400">As ações de captação aparecerão neste histórico.</p>}</div></section>;
}
